# Generated by Django 4.2.4 on 2023-09-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0002_employee_menucategory_menuitem_order_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(default='customer', max_length=50),
        ),
    ]
