# Generated by Django 4.2.4 on 2023-09-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0002_employee_menucategory_menuitem_order_restaurant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('expiration_date', models.DateField()),
                ('reorder_quantity', models.PositiveIntegerField(default=10)),
            ],
        ),
    ]
