# Generated by Django 4.2.4 on 2023-09-08 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0003_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
