# Generated by Django 4.2.4 on 2023-09-09 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0003_customuser_profile_customuser_user_type'),
        ('hotelmanagement', '0004_delete_stock'),
    ]

    operations = [
    ]
