# Generated by Django 4.2.4 on 2023-09-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0006_alter_customuser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(default='profiles/default_profile.jpg', upload_to='profiles/'),
        ),
    ]
