# Generated by Django 4.2.4 on 2023-09-19 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0009_alter_user_type_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.ForeignKey(default='Super', on_delete=django.db.models.deletion.CASCADE, to='hotelmanagement.user_type'),
        ),
    ]
