# Generated by Django 4.2.4 on 2023-10-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0013_alter_customuser_is_active_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='message_type',
            field=models.CharField(choices=[('Authorization', 'Authorization'), ('Request', 'Request'), ('Denial', 'Denial'), ('Unknown', 'Unknown')], default=('Unknown', 'Unknown'), max_length=255),
        ),
        migrations.AddField(
            model_name='messages',
            name='receiver_category',
            field=models.CharField(choices=[('CEO', 'CEO'), ('StoreKeeper', 'StoreKeeper'), ('Chef', 'Chef'), ('Waiter', 'Waiter'), ('Customer', 'Customer'), ('None', 'None')], default=('None', 'None'), max_length=255),
        ),
        migrations.AddField(
            model_name='messages',
            name='sender_category',
            field=models.CharField(choices=[('CEO', 'CEO'), ('StoreKeeper', 'StoreKeeper'), ('Chef', 'Chef'), ('Waiter', 'Waiter'), ('Customer', 'Customer'), ('None', 'None')], default=('None', 'None'), max_length=255),
        ),
    ]
