# Generated by Django 4.2.4 on 2023-10-11 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0014_messages_message_type_messages_receiver_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='receiver_category',
        ),
    ]
