# Generated by Django 4.2.4 on 2023-10-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0014_remove_menuimage_menu_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
