# Generated by Django 4.2.4 on 2023-10-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0015_remove_messages_receiver_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='receiver',
        ),
        migrations.AlterField(
            model_name='messages',
            name='message_type',
            field=models.CharField(choices=[('Authorization', 'Authorization'), ('Request', 'Request'), ('Denial', 'Denial'), ('Information', 'Information'), ('Unknown', 'Unknown')], default=('Information', 'Information'), max_length=255),
        ),
        migrations.AlterField(
            model_name='messages',
            name='sender_category',
            field=models.CharField(choices=[('CEO', 'CEO'), ('Storekeeper', 'Storekeeper'), ('Chef', 'Chef'), ('Waiter', 'Waiter'), ('Customer', 'Customer'), ('None', 'None')], default=('None', 'None'), max_length=255),
        ),
    ]
