# Generated by Django 4.2.4 on 2023-10-12 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0014_messages_message_type_messages_receiver_category_and_more'),
        ('hotelmanagement', '0016_menuitem_average_rating_menuitemrating'),
    ]

    operations = [
    ]
