# Generated by Django 4.2.4 on 2023-10-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0016_remove_messages_receiver_alter_messages_message_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='date_sent',
            field=models.DateField(auto_now=True),
        ),
    ]
