# Generated by Django 4.2.4 on 2023-10-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0017_remove_order_order_date_remove_order_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
