# Generated by Django 4.2.4 on 2023-10-12 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0017_merge_20231012_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='table',
            name='restaurant',
        ),
    ]
