# Generated by Django 4.2.4 on 2023-10-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0018_remove_order_restaurant_remove_table_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.AddField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='received_time',
            field=models.DateTimeField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='send',
            field=models.BooleanField(default=False),
        ),
    ]
