# Generated by Django 4.2.4 on 2023-10-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0019_remove_order_order_date_order_order_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='received_time',
            field=models.DateTimeField(null=True),
        ),
    ]
