# Generated by Django 4.2.4 on 2023-10-19 15:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0021_alter_order_ordered_time_delete_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 19, 15, 32, 0, 300682)),
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_sent', models.DateTimeField(auto_now=True)),
                ('time_opened', models.DateTimeField(blank=True, null=True)),
                ('opened', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('message_type', models.CharField(choices=[('Authorization', 'Authorization'), ('Request', 'Request'), ('Denial', 'Denial'), ('Information', 'Information'), ('Unknown', 'Unknown')], default=('Information', 'Information'), max_length=255)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelmanagement.order')),
                ('receiver_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelmanagement.user_type')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
