# Generated by Django 4.2.4 on 2023-10-12 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0021_alter_order_order_time_alter_order_received_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateField(default=datetime.datetime(2023, 10, 12, 12, 20, 44, 521919)),
        ),
        migrations.AlterField(
            model_name='order',
            name='received_time',
            field=models.DateField(default=datetime.datetime(2023, 10, 12, 12, 20, 44, 521919)),
        ),
    ]
