# Generated by Django 4.2.4 on 2023-10-12 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0022_alter_order_order_time_alter_order_received_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='received_time',
        ),
    ]
