# Generated by Django 4.2.4 on 2023-10-12 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0023_remove_order_order_time_remove_order_received_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_time',
            field=models.DateField(default=datetime.datetime(2023, 10, 12, 12, 22, 27, 177644)),
        ),
        migrations.AddField(
            model_name='order',
            name='received_time',
            field=models.DateField(default=datetime.datetime(2023, 10, 12, 12, 22, 27, 177644)),
        ),
    ]
