# Generated by Django 4.2.4 on 2023-10-27 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0028_alter_order_ordered_time_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 27, 10, 11, 53, 411868)),
        ),
    ]
