# Generated by Django 4.2.4 on 2023-10-30 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0030_alter_menuitem_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 30, 11, 57, 21, 310096)),
        ),
    ]
