# Generated by Django 4.2.4 on 2023-10-30 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0032_alter_order_ordered_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuimage',
            name='image',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 30, 15, 39, 25, 43199)),
        ),
    ]
