# Generated by Django 4.2.4 on 2023-10-30 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0033_alter_menuimage_image_alter_order_ordered_time'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='menuimage',
            name='image',
            field=models.FileField(upload_to='menus/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 30, 16, 10, 42, 271423)),
        ),
    ]
