# Generated by Django 4.2.4 on 2023-10-30 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0034_alter_customuser_managers_alter_menuimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuimage',
            name='image',
            field=models.ImageField(upload_to='menus/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 30, 17, 29, 48, 641450)),
        ),
    ]
