# Generated by Django 4.2.4 on 2023-11-03 08:50

import datetime
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0035_alter_menuimage_image_alter_order_ordered_time'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='customer_profit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='menuitemrating',
            name='comment',
            field=models.CharField(default='The food is too good', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 11, 50, 51, 399069)),
        ),
    ]
