# Generated by Django 4.2.4 on 2023-11-03 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0036_alter_customuser_managers_customuser_customer_profit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemrating',
            name='comment',
            field=models.TextField(default='The food is too good', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 12, 16, 54, 804581)),
        ),
    ]
