# Generated by Django 4.2.4 on 2023-11-03 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0037_alter_menuitemrating_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='cost',
            new_name='ingredient_cost',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='orders_number',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 12, 26, 55, 460512)),
        ),
    ]
