# Generated by Django 4.2.4 on 2023-11-03 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0038_rename_cost_menuitem_ingredient_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='item_profit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 12, 36, 34, 475332)),
        ),
    ]
