# Generated by Django 4.2.4 on 2023-11-03 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0039_menuitem_item_profit_alter_order_ordered_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='item_profit',
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 12, 43, 32, 177838)),
        ),
    ]
