# Generated by Django 4.2.4 on 2023-11-03 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0040_remove_menuitem_item_profit_alter_order_ordered_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='item_profit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 3, 12, 52, 38, 513230)),
        ),
    ]
