# Generated by Django 4.2.4 on 2023-11-04 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0044_alter_order_ordered_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 13, 53, 2, 351515)),
        ),
    ]
