# Generated by Django 4.2.4 on 2023-11-29 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0051_alter_customuser_is_active_alter_order_ordered_time'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 7, 57, 13, 533967)),
        ),
    ]
