# Generated by Django 4.2.4 on 2023-11-30 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0052_alter_customuser_managers_alter_order_ordered_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 30, 15, 33, 22, 653574)),
        ),
    ]
