# Generated by Django 4.2.4 on 2023-12-19 14:39

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0052_alter_customuser_managers_alter_order_ordered_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='menuimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 19, 14, 39, 51, 531380)),
        ),
    ]
