# Generated by Django 4.2.4 on 2023-12-19 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0053_alter_customuser_profile_alter_menuimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 19, 15, 12, 59, 851212)),
        ),
    ]
