# Generated by Django 4.2.4 on 2023-12-20 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0055_alter_customuser_managers_order_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.DecimalField(decimal_places=15, default=35.810966491699226, max_digits=18),
        ),
        migrations.AlterField(
            model_name='order',
            name='latitude',
            field=models.DecimalField(decimal_places=15, default=-6.216848786038759, max_digits=18),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 20, 5, 29, 16, 306644)),
        ),
    ]
