# Generated by Django 4.2.4 on 2023-12-24 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0053_alter_order_ordered_time'),
        ('hotelmanagement', '0056_order_longitude_alter_order_latitude_and_more'),
    ]

    operations = [
    ]
