# Generated by Django 4.2.4 on 2023-12-20 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0056_order_longitude_alter_order_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 20, 9, 12, 22, 544305)),
        ),
    ]
