# Generated by Django 4.2.4 on 2023-12-24 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0057_merge_20231224_0904'),
        ('hotelmanagement', '0058_alter_order_ordered_time'),
    ]

    operations = [
    ]
