# Generated by Django 4.2.4 on 2023-12-24 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0058_alter_menuitemrating_comment_and_more'),
        ('hotelmanagement', '0059_merge_20231224_0808'),
    ]

    operations = [
    ]
