# Generated by Django 4.2.4 on 2023-12-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0061_cupon_menu_item_alter_cupon_id_alter_menuitem_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupon',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
