# Generated by Django 4.2.4 on 2023-12-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0062_alter_cupon_id_alter_menuitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
