# Generated by Django 4.2.4 on 2023-12-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmanagement', '0064_alter_menuitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='customer_profit',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='ingredient_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='item_profit',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='orders_number',
            field=models.IntegerField(),
        ),
    ]
