# Generated by Django 4.2.4 on 2023-10-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockManagerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPurchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=255)),
                ('goods_bought', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('date_delivered', models.DateField(auto_now=True)),
            ],
        ),
    ]
