# Generated by Django 4.2.4 on 2023-10-09 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StockManagerApp', '0003_alter_stockpurchases_goods_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpurchases',
            name='recorder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
