# Generated by Django 4.2.4 on 2023-10-09 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StockManagerApp', '0006_delete_stockpurchases'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPurchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=255)),
                ('goods_bought', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('date_delivered', models.DateField(auto_now=True)),
                ('recorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
