# Generated by Django 4.2.4 on 2023-10-10 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockManagerApp', '0007_stockpurchases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockpurchases',
            name='recorder',
        ),
    ]
