# Generated by Django 4.2.4 on 2023-10-10 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StockManagerApp', '0008_remove_stockpurchases_recorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefStockResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('expiration_date', models.DateField()),
                ('reorder_quantity', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='RequestStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockManagerApp.stock')),
            ],
        ),
    ]
