# Generated by Django 4.2.4 on 2023-11-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockManagerApp', '0010_usechefresources'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=12),
            preserve_default=False,
        ),
    ]
