# Generated by Django 4.2.4 on 2023-11-30 12:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('departmentID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('departmentName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('employeeID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('middleName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('social_security_number', models.CharField(max_length=20)),
                ('National_id_number', models.CharField(max_length=15)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeManagement.departments')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('CategoryName', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('CategoryName', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MainStore',
            fields=[
                ('ItemId', models.AutoField(primary_key=True, serialize=False)),
                ('Item_name', models.CharField(max_length=100)),
                ('BuyPrice', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('ReceivedQuantityInStock', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('RemainedQuantityInStock', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('Received_date', models.DateField(auto_now_add=True)),
                ('Received_Condition', models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged'), ('faulty', 'Faulty')], max_length=10)),
                ('ItemCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeManagement.itemcategory')),
                ('Received_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeManagement.employeedetails')),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('UnitName', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('days_off', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('overtime_hours', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('Month', models.DateField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeManagement.employeedetails')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAlocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(max_length=100)),
                ('QuantityAllocated', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('Issued_by', models.CharField(max_length=100)),
                ('Received_date', models.DateField(auto_now=True)),
                ('Received_Condition', models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged'), ('faulty', 'Faulty')], max_length=10)),
                ('ItemCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeManagement.itemcategory')),
                ('ItemId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='EmployeeManagement.mainstore')),
                ('Received_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeManagement.employeedetails')),
                ('Receiver_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeManagement.departments')),
                ('Unit_Measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeManagement.unitofmeasure')),
            ],
        ),
        migrations.AddField(
            model_name='mainstore',
            name='Unit_Measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeManagement.unitofmeasure'),
        ),
        migrations.CreateModel(
            name='LegalDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Application_Letter', models.FileField(upload_to='legal_documents/')),
                ('SponsorLetter', models.FileField(upload_to='legal_documents/')),
                ('Local_government_Approval_Letter', models.FileField(upload_to='legal_documents/')),
                ('Curriculam_vitae', models.FileField(blank=True, null=True, upload_to='legal_documents/')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EmployeeManagement.employeedetails')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('IncomeAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IncomeCategoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeManagement.itemcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ExitRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_date', models.DateField()),
                ('exit_reason', models.TextField()),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EmployeeManagement.employeedetails')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentIssuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniform_details', models.TextField()),
                ('equipment_issuance_date', models.DateField()),
                ('equipment_return_date', models.DateField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeManagement.employeedetails')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentDetails',
            fields=[
                ('EquipmentID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('EquipmentName', models.CharField(max_length=20)),
                ('EquipmentCondition', models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged'), ('faulty', 'Faulty')], max_length=15)),
                ('Location', models.CharField(blank=True, max_length=100)),
                ('CategoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeManagement.equipmentcategory')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50)),
                ('date_of_hire', models.DateField()),
                ('employment_status', models.CharField(max_length=20)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EmployeeManagement.employeedetails')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=13, unique=True)),
                ('Email_Address', models.EmailField(max_length=100, unique=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeManagement.employeedetails')),
            ],
        ),
        migrations.CreateModel(
            name='employee_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegionOfBirth', models.CharField(max_length=100)),
                ('DistrictOfBirth', models.CharField(max_length=100)),
                ('wardOfBirth', models.CharField(max_length=100)),
                ('CurrentRegion', models.CharField(max_length=100)),
                ('CurrentDistrict', models.CharField(max_length=100)),
                ('CurrentWard', models.CharField(max_length=100)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EmployeeManagement.employeedetails')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=50)),
                ('Valid_phoneNumber', models.CharField(max_length=13, unique=True)),
                ('Valid_Email_Address', models.EmailField(max_length=100, unique=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeManagement.employeedetails')),
            ],
        ),
    ]
