# Generated by Django 4.2.4 on 2023-12-29 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeManagement', '0003_employeedetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetails',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='middleName',
        ),
    ]
