# Generated by Django 4.2.4 on 2023-12-29 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EmployeeManagement', '0005_alter_employeedetails_national_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='National_id_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EmployeeManagement.departments'),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='social_security_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
